import 'package:intl/intl.dart';
import '../../core/utils/date_formatter.dart';
import '../../core/utils/unit_converter.dart';
import 'daily_forecast_entity.dart';
import 'weather_entity.dart';

class HikeDossierEntity {
  final String locationName;
  final DateTime generatedAt;
  final String currentTempFormatted;
  final String conditionSummary;
  final List<DailyForecastEntity> forecast7Day;
  final List<String> recommendedGear;
  final String sunriseTime;
  final String sunsetTime;
  final String safetyAdvisory;
  final String barometricTrend;

  const HikeDossierEntity({
    required this.locationName,
    required this.generatedAt,
    required this.currentTempFormatted,
    required this.conditionSummary,
    required this.forecast7Day,
    required this.recommendedGear,
    required this.sunriseTime,
    required this.sunsetTime,
    required this.safetyAdvisory,
    required this.barometricTrend,
  });

  factory HikeDossierEntity.fromWeather(
    WeatherEntity weather, {
    TemperatureUnit tempUnit = TemperatureUnit.celsius,
    SpeedUnit speedUnit = SpeedUnit.kmh,
  }) {
    final curTemp = UnitConverter.formatTemperatureString(
      weather.temperature,
      tempUnit,
    );

    final advisory = weather.weatherAlerts.hasAlerts
        ? weather.weatherAlerts.activeAlerts.first.title
        : (weather.minutePrecipitation.hasPrecipitation
            ? 'Precipitation expected along mountain trails. Pack waterproof gear.'
            : 'Favorable conditions. Maintain adequate hydration and trail pacing.');

    final timeFmt = DateFormat('hh:mm a');
    final sunriseStr = timeFmt.format(weather.astronomy.sunrise);
    final sunsetStr = timeFmt.format(weather.astronomy.sunset);

    return HikeDossierEntity(
      locationName: weather.location.name,
      generatedAt: weather.timestamp,
      currentTempFormatted: curTemp,
      conditionSummary: weather.humanSummary,
      forecast7Day: weather.dailyForecast,
      recommendedGear: weather.recommendedGear,
      sunriseTime: sunriseStr,
      sunsetTime: sunsetStr,
      safetyAdvisory: advisory,
      barometricTrend:
          '${weather.biophilicHealth.pressureDelta12h >= 0 ? "+" : ""}${weather.biophilicHealth.pressureDelta12h.toStringAsFixed(1)} hPa (12h trend: ${weather.biophilicHealth.headacheRiskStatus})',
    );
  }

  String toHtmlDocument(TemperatureUnit tempUnit) {
    final rows = forecast7Day.map((d) {
      final dayStr = DateFormatter.formatDayOfWeek(d.date);
      final minStr = UnitConverter.formatTemperatureString(d.minTemp, tempUnit);
      final maxStr = UnitConverter.formatTemperatureString(d.maxTemp, tempUnit);
      return '''
        <tr>
          <td><strong>$dayStr (${DateFormatter.formatShortDate(d.date)})</strong></td>
          <td>${d.condition.displayName}</td>
          <td>$minStr / $maxStr</td>
          <td>UV ${d.maxUvIndex.round()}</td>
        </tr>
      ''';
    }).join('\n');

    final gearItems = recommendedGear.map((g) => '<li>[ ] $g</li>').join('\n');

    return '''
      <h1>HORIZON OFF-GRID EXPEDITION DOSSIER</h1>
      <div class="subtitle">Location: <strong>$locationName</strong> | Generated: ${DateFormatter.formatShortDate(generatedAt)} | Current: $currentTempFormatted</div>

      <div class="section-box">
        <strong>OVERVIEW & TRAIL ADVISORY</strong><br>
        $conditionSummary<br><br>
        <strong>Safety Corridor:</strong> $safetyAdvisory<br>
        <strong>Barometric Pressure:</strong> $barometricTrend
      </div>

      <h2>7-DAY MICROCLIMATE MATRIX</h2>
      <table>
        <thead>
          <tr>
            <th>Day</th>
            <th>Condition</th>
            <th>Temp (Min / Max)</th>
            <th>Solar UV</th>
          </tr>
        </thead>
        <tbody>
          $rows
        </tbody>
      </table>

      <h2>SOLAR DAYLIGHT WINDOW</h2>
      <div class="section-box">
        <strong>First Sunrise:</strong> $sunriseTime &nbsp;&nbsp;|&nbsp;&nbsp; <strong>Last Sunset:</strong> $sunsetTime<br>
        <em>Ensure camp setup is completed at least 45 minutes prior to dusk.</em>
      </div>

      <h2>ESSENTIAL GEAR & SURVIVAL PACKLIST</h2>
      <ul>
        $gearItems
        <li>[ ] 2L Hydration reservoir & purification tablets</li>
        <li>[ ] Topographic trail map & analog compass</li>
        <li>[ ] First aid kit & emergency thermal blanket</li>
      </ul>

      <div class="footer">
        Generated by Horizon Weather • Zero-Connectivity Offline Expedition Dossier
      </div>
    ''';
  }

  String toMarkdownDocument(TemperatureUnit tempUnit) {
    final buffer = StringBuffer();
    buffer.writeln('# HORIZON OFF-GRID EXPEDITION DOSSIER');
    buffer.writeln('**Location:** $locationName');
    buffer.writeln('**Generated:** ${generatedAt.toIso8601String()}');
    buffer.writeln('**Current Climate:** $currentTempFormatted');
    buffer.writeln('');
    buffer.writeln('## Overview');
    buffer.writeln(conditionSummary);
    buffer.writeln('');
    buffer.writeln('**Safety Corridor:** $safetyAdvisory');
    buffer.writeln('**Barometric Status:** $barometricTrend');
    buffer.writeln('');
    buffer.writeln('## 7-Day Microclimate Matrix');
    buffer.writeln('| Day | Condition | Min/Max Temp | Solar UV |');
    buffer.writeln('| :--- | :--- | :--- | :--- |');
    for (final d in forecast7Day) {
      final dayStr = DateFormatter.formatDayOfWeek(d.date);
      final minStr = UnitConverter.formatTemperatureString(d.minTemp, tempUnit);
      final maxStr = UnitConverter.formatTemperatureString(d.maxTemp, tempUnit);
      buffer.writeln(
          '| $dayStr (${DateFormatter.formatShortDate(d.date)}) | ${d.condition.displayName} | $minStr / $maxStr | UV ${d.maxUvIndex.round()} |');
    }
    buffer.writeln('');
    buffer.writeln('## Daylight Window');
    buffer.writeln('- **Sunrise:** $sunriseTime');
    buffer.writeln('- **Sunset:** $sunsetTime');
    buffer.writeln('');
    buffer.writeln('## Essential Gear Checklist');
    for (final item in recommendedGear) {
      buffer.writeln('- [ ] $item');
    }
    buffer.writeln('- [ ] 2L Water reservoir & purification tablets');
    buffer.writeln('- [ ] Topographic offline map & compass');
    buffer.writeln('- [ ] Emergency thermal foil blanket');
    buffer.writeln('');
    buffer.writeln('---');
    buffer.writeln('*Horizon Weather • Offline Expedition Dossier*');
    return buffer.toString();
  }
}
